WFDR-221-ForgotPassword
NickMoo5/CMPT-276-Project pull request #17
Opened 2023-07-13 02:45 UTC by danielqyu

## Summary of changes
Added forgot password and corresponding files needed

## Trello Task link
221.1-6

## Corresponding User Story Number and Title
User case 3: Forgot password

## Detailed list of changes
- Added reveal password option on the login (toggle)
##### Added inputEmailForPin.html
- prompts user to input email associated with their account
- if successful, user will be sent to pinConfirmation.html and email will be sent to user's email with user's associated pin
- if unsuccessful, error message will display showing that email entered is not part of an account. user will stay on page
##### Added pinConfirmation.html
- prompts user to input pin that was sent via email, pulls user's pin from database and checks if it is equal to entered pin(success)
- if successful, user will be sent to changePasssword.html and prompted to change password
- if unsuccessful, error message will display showing inputted pin does not match pin from database. user will stay on page
##### Added changePassword.html
- prompts user to change password, based off of set initial password when creating account from addUsers.html
- if user creates password that satisfies requirements, user's password is changed and a new pin is generated.
- user is redirected to login

2023-07-14 02:55 UTC, setaDM requested changes, later dismissed
The email is sent fine to the user and it also properly updates the password. Reveal password button works correctly too.
 
However there is a huge issue that needs to be addressed. When the user hits forgot password and is waiting for the pin if they click login from there then they automatically sign in... This is  due to the user session being stored. Not entirely sure how to fix it except that the user session cannot be stored when the user has not signed in yet! Otherwise at any point the user can simply open a new tab and go to the login page and they will automatically be signed in. 
This is a solution that I'm not entirely sure will work, but you could create a searchByPinId function in userRepository.java that way you can find the user again once they successfully enter their pin and then you shouldn't need to store the session user (?) but I'm not entirely.

I can help you implement a fix that might work if you're unable to. It just seems like it'd be a lot easier for you since you understand your code a lot better lol.

Also Line 15 needs to be changed to have a / in front of the user/pinConfirmation that way it looks like /user/pinConfirmation. This is for when there is a pin error and then the user successfully enters the right pin for the user to be brought to the correct endpoint. (Currently brought to user/user/pinconfirmation in this scenario)

2023-07-14 21:40 UTC, setaDM approved these changes
Tested the new code and was unable to find any bugs or anything that didn't work.

2023-07-15 01:58 UTC, plee99 approved these changes

2023-07-15 02:30 UTC, hilokiyz commented
Ran it out, looks good to me

2023-07-15 16:27 UTC, hilokiyz approved these changes

2023-07-16 04:50 UTC, merged