- better UI for trip setting validation errors
NickMoo5/CMPT-276-Project pull request #31
Opened 2023-07-24 20:06 UTC by plee99

## Summary of changes
- small PR where user landing error messages are displayed with better UI
## Trello Task link
https://trello.com/c/OQ66APWW/72-302-userlanding-validations
## Corresponding User Story Number and Title
User case 5: Generate Itinerary 

## Detailed list of changes
modified js to display error messages properly

2023-07-25 08:58 UTC, NickMoo5 requested changes
![image](https://github.com/NickMoo5/CMPT-276-Project/assets/78270735/a5b15a10-edca-4980-b765-9a57de03883e)
When the error msg shows the location icon in the city textbox doesn't move making it look weird. 

Having the msg appear above the City textbox when it could be meant for the bottom 3 inputs makes it look weird and confusing. Are you able to come up with a solution that indicates to the user exactly what's empty.

2023-07-25 23:45 UTC, danielqyu requested changes
the "location" icon moves up when you try submitting with an error.

is it possible to have the error message pop up on the specific missing areas rather than location?
also if possible, the error message should disappear when the user fills in the field(s)

2023-07-27 23:46 UTC, plee99 commented
- error messaged now indicate to the user exactly what's missing
- icons moving is fixed
- real time errors implemented

![image](https://github.com/NickMoo5/CMPT-276-Project/assets/106282547/a7da8ee3-7f02-4bb8-9647-466093c8a646)

![image](https://github.com/NickMoo5/CMPT-276-Project/assets/106282547/7f4bd0a4-d280-4772-9ec5-a43076409c66)

2023-07-28 04:47 UTC, setaDM requested changes
Errors look like they work fine and they were updated properly however when I was typing in the city I noticed that your branch doesn't have my autocomplete code.  It appears you removed it. Not sure if it was intentional or if it was a mistake during a merge conflict, but either way you should add it back. If youre unsure about which lines youre missing they are lines 32 and 257 in userLanding.html that you removed.

2023-07-28 06:03 UTC, plee99 commented
added autocomplete should be good to merge

2023-07-28 11:03 UTC, NickMoo5 requested changes
Add back in the code I highlighted in my review as that's needed for some error handling on backend

2023-07-28 11:03 UTC, NickMoo5 commented on src/main/resources/templates/user/userLanding.html
> -					<button class="btn btn-lg btn-primary mb-2" type="submit">Go back to Trip Planning Page<i class="bi bi-arrow-right ps-3"></i></button>
This needs to be added back; seems you deleted from the merge

2023-07-28 11:16 UTC, merged