WFDR-303-AboutUs
NickMoo5/CMPT-276-Project pull request #33
Opened 2023-07-26 19:07 UTC by danielqyu

## Summary of changes
Add aboutUs page

## Trello Task link
303-AboutUs

## Corresponding User Story Number and Title
10-About Us

## Detailed list of changes

Add aboutUs, access from ->footer on userlanding (about us)
Added static navbar when scrolling + small shadow

2023-07-28 04:58 UTC, setaDM requested changes
I don't think the about us page should have "meet the team" at the bottom where it just sends the user back to the same page. Maybe we can add a meet the team page and have a button in the bottom middle of the mission photo where it'll send users to that page. The meet the team page could have our names a small description and maybe a photo? (We can discuss during meeting tmrw). Also I think the text should be centralized underneath "traveling made better" to match the mission portion since the text there is centralized. Otherwise it looks good.

2023-07-28 11:11 UTC, NickMoo5 requested changes
I agree with David that the text under The big header "Travelling Made Better" should be centered.

Additionally the footers on all pages will need to be updated with this, currently only user landing has the link added to the footer. 

This will also need to be slightly updated after Peter's fluff page is merged as well.

Some points for further discussion during meeting is whether being logged in is required to view the webpage and potentially a navbar.

2023-07-30 09:56 UTC, NickMoo5 requested changes
dont forget to upload the imgs :))

2023-07-30 09:56 UTC, NickMoo5 commented on src/main/resources/templates/user/aboutUs.html
> +								<p style="font-size: smaller;">We enourage people to explore the world around them.</p>
spelling :))

2023-07-30 09:56 UTC, NickMoo5 commented on src/main/resources/templates/user/aboutUs.html
> +                <h6>David Muleh</h6>
spelling :))

2023-07-30 09:56 UTC, NickMoo5 commented on src/main/resources/templates/user/aboutUs.html
> +                <h6>Nicolas Mah</h6>
spelling >:((((((( how could u im dissapointed

2023-07-30 19:46 UTC, setaDM approved these changes
About us page and contact page looks good to me. The photo resolution is slightly distorted for some of the photos on the contact page, but it's not really a big deal and I also don't think you can really do anything about it since youre trying to fit it into the circle. If youre able to fix it then you can before you merge, but otherwise I think it looks good.

2023-07-30 22:43 UTC, plee99 approved these changes
the page looks awesome! I really like the design of the title, good work

2023-07-30 23:15 UTC, merged